#!/usr/bin/env python3
"""Rebuild _indexes/decisions.md from Log/**decision|kill** lines.

Deterministic. No LLM. No secrets. Safe to run anytime.
"""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

VAULT = Path(__file__).resolve().parent.parent.parent
LOG = VAULT / "Log"
OUT = VAULT / "_indexes" / "decisions.md"

# - **decision** (HH:MM): text
# - **kill** (HH:MM): text
# - **decision**: text
ENTRY = re.compile(
    r"^- \*\*(decision|kill)\*\*(?:\s*\(([^)]+)\))?:\s*(.+)$",
    re.IGNORECASE,
)


def main() -> int:
    rows: list[tuple[str, str, str, str]] = []  # date, time, kind, body
    if LOG.exists():
        for path in sorted(LOG.glob("????-??-??.md")):
            day = path.stem
            for line in path.read_text(encoding="utf-8").splitlines():
                m = ENTRY.match(line.strip())
                if not m:
                    continue
                kind, when, body = m.group(1).lower(), m.group(2) or "", m.group(3).strip()
                rows.append((day, when, kind, body))

    lines = [
        "---",
        'title: "Decisions index"',
        "type: index",
        f"updated: {date.today().isoformat()}",
        "---",
        "",
        "# Decisions index",
        "",
        "Auto-built from `Log/` lines matching `**decision**` or `**kill**`.",
        "Source of truth remains append-only Log — do not edit this file by hand.",
        "",
        f"Rebuilt: **{date.today().isoformat()}**. Entries: **{len(rows)}**.",
        "",
        "```bash",
        "python3 scripts/intelligence/build_decisions_index.py",
        "```",
        "",
        "| Date | Time | Kind | Entry |",
        "|------|------|------|-------|",
    ]
    for day, when, kind, body in reversed(rows):  # newest first
        safe = body.replace("|", "\\|")
        lines.append(f"| {day} | {when or '—'} | {kind} | {safe} |")

    if not rows:
        lines.append("| — | — | — | *(no decision/kill lines in Log yet)* |")

    lines.extend(
        [
            "",
            "## Contract",
            "",
            "- **decision** — operator choice with lasting effect (product kill,",
            "  structure change, commitment). Lives in Log only.",
            "- **kill** — abandoned idea/work with reason. Lives in Log only.",
            "- **Theses/** — evolving hypotheses (views that can reverse), not",
            "  one-shot decisions.",
            "- See [[AGENTS]] Operator log + Intelligence layer.",
            "",
        ]
    )

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(VAULT)} ({len(rows)} entries)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
